### ISSUE TITLE
plano-sistema | Orçamentos para hospedagem de site + banco de dados MySQL

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#1]
Elaboração de cotações e avaliação dos serviços

- Smarter ASP https://www.smarterasp.net/hosting_plans
- UOL https://uolhost.uol.com.br/hospedagem-de-sites.html
- Oracle Cloud https://cloud.oracle.com/pt_BR/home

**Comment by ghost** [comment]
Serviços mínimos a contratar
- Backup
- Acesso simultâneos ao banco MySQL
- Sendmail

**Comment by ghost** [comment]
O @bussola está com dificuldades de criar as triggers de auditora no MySQL.
@VanderleiDenir é preciso identificar se de fato é uma restrição do plano atual e avaliar a inclusão de funcionalidades básicas de um banco RDBMS para o projeto.

![image](https://user-images.githubusercontent.com/34185310/37726592-814c60c4-2d14-11e8-9ed6-3dae7ee1cb3a.png)

**Comment by VanderleiDenir** [comment]
De acordo com o suporte da hospedagem atual não ha suporte para trigger nos bancos MySQL. 
Estaremos analisando um upgrade para o plano semi dedicado para resolver essa e outras limitações.

**Comment by ghost** [comment]
Olá Pessoal!
Estou fazendo as integrações de dados do TSE das Candidaturas e Contas Eleitorais para o Banco Access e durante este processo fiz algumas adequações importantes em tabelas e colunas do PNE.

Quero atualizar o banco MySQL mas não estou conseguindo utilizar a ferramenta do WorkBench que pouparia muito tempo para realizar a migração do Access para MySQL.
Pois o usuário MySQL, em razão do plano, não tem os privilégios básicos que permitam realizar essa migração, e com isso terei que fazer a atualização manualmente tabela por tabela!

Ressalto a importância de sabermos detalhadamente quais funcionalidades do MySQL o provedor não está incluindo no plano para evitarmos surpresas no desenvolvimento futuro.
Ou considerar cotar outros provedores para a OPS.

**Comment by ghost** [comment]
Desenvolvimento do banco em MySQL aguardando definição de um servidor/provedor Internet que não tenha as limitações de espaço / funcionalidades e carga de dados o qual está impedindo avanços nesta versão do banco.
Seguem os trabalhos na versão MS Access

**Comment by ghost** [comment]
De acordo com as conversas com @LucioBig e @VanderleiDenir sobre a terceirização da infraestrutura tecnológica do projeto (Banco de Dados/Aplicação) a partir da contratação de uma estrutura de TI equilibrada entre preço/funcionalidades a fim de comportar o tamanho que o banco do PNE unificando-o com o MySQL OPS e com isso manter tudo integrado numa aplicação disponível 24/7/365, temos como síntese das conversas o seguinte:

Antes de partirmos para a contratação de um serviço para grandes volumes de dados ficou subentendido entre @VanderleiDenir e @AlexKiredjian realizar testes com o WordPress aproveitando a experiência de @LucioBig com essa plataforma, no qual, adequaremos o Layout/Template semelhante a uma WebStore como segue:

1-Conceito proposto por @AlexKiredjian:  
Utilizar ou adequar um modelo/template do WordPress parecido com o de uma loja virtual, no qual consideraremos cada post de produto como sendo um candidato/político para cada estado ou nacionalmente, que possam ser "vendidos" postos na urna nesta loja.

Estes posts possuirão uma foto, ao lado com dados comuns do candidato, e numa tabela abaixo com três colunas (Categoria / Descrição / Informação) com todos os valores oficiais obtidos via integrações com o banco MsAccess para cada candidato. Cada post possuirá marcadores de classificação, como por exemplo, Governador; SP; PT; Fixa Suja; Não votar em 2018, etc. 
O usuário poderá adicionar em seu "carrinho" mediante escolhas a partir de comparações entre políticos/pots para determinados assuntos que achar importante, onde poderá adicionar ao seu carrinho, ou seja "votar" nos 5 cargos eletivos para este ano, e se possível também comparar com outros carrinhos de usuários, desde que queiram compartilhar suas escolhas, mas sem saber o usuário mantendo dessa forma a privacidade da intenção de voto.

2-Como faremos isso?
@LucioBig poderá criar um post modelo com foto do candidato / dados gerais e na tabela de três colunas Categoria / Descrição / Informação, como exemplo:
Apontamentos Judiciais
Processos STF (4)
	5585, 8855, 8858, 5522
	Processos Vara Civil (2)
		5554545.5454/2017, 56546465.654654/2016
Despesas CEAP
	Passagens Aéras 2016 
		R$ 855.555,22

@AlexKiredjian
	Fará os processos ETL referentes aos dados oficiais de acordo com a tabela de Atributos para cada candidato.
	Estudar a codificação, plugins a fim de Identificar formas de fazer que o wordpress se comporte como uma loja de políticos, e que receba a partir de arquivos json os novos posts de políticos bem como atualizar seus dados.
	Os cadastros do MsAccess ficarão disponível em nosso antigo Oracle para Lucio, Vanderlei, Alex de forma centralizada para que possamos trabalhar em conjunto nas descrições e categorias de dados a integrar. 

@VanderleiDenir
	Estudar a codificação, plugins a fim de Identificar formas de fazer que o wordpress se comporte como uma loja de políticos, e que receba a partir de arquivos json os novos posts de políticos bem como atualizar seus dados.
	Fará os processos ETL referentes aos dados oficiais de acordo com a tabela de Atributos para cada candidato.


3-Como funcionará

Cadastro de novo político
No wordpress deverá ser criado uma nova postagem somente com o nome político do cidadão e seu estado vide modelo em https://wordpress.com/post/projetonovoeleitor.com.br/339 (este modelo está visivel somente para editores ou adm do site)
O msaccess fará periodicamente leituras nos posts no intuito de complementar / atualizar os dados de cada post/candidato conforme novas integrações de dados oficiais são carregadas no banco em msaccess, e de acordo com novas informações o post será alimentado.


Comparar posts
Com o plugin de comparação definido, o usuário poderá comparar os candidatos e também com o plug-in de carrinho definido o usuário também poderá salvar um candidato ou vários dentro do carrinho para futuro uso de sua cola eleitoral.

As demais operações de edição/exclusão e textos em geral para cada candidato ficará a cargo do editor do wordpress.

**Comment by joepreludian** [comment]
@alexkiredjian Olá amigo! Olá @LucioBig e todos os outros.

Só uma coisa que eu não entendi. A abordagem de usar o Wordpress substituiria a fonte inicial dos dados? Como isso chegaria para a ponta, do telefone?

Irei propor uma ideia sem custo inicial, e que é está sendo uma tendência para aplicações web modernas. O que acha de usarmos as máquinas para processar os dados e subir esses dados processados de maneira estática para um servidor?

Até mesmo poderíamos utilizar serviços de build "como travis" para publicar os itens processados.

À propósito, parabéns pela iniciativa!

**Comment by ghost** [comment]
Opa @joepreludian !!
_**A abordagem de usar o Wordpress substituiria a fonte inicial dos dados?**_
Não, os posts do blog serão "escritos" a partir de um processo que ainda não existe, mas deverá ler o banco em MySQL, sumarizando os dados de cada candidato, e via API do serviço de Blog criar ou alterar algum post com tais informações.

**_Como isso chegaria para a ponta, do telefone?_**
De forma tradicional, a partir de navegadores WEB em computadores ou telefones dos quais receberão as páginas via processamento do Blog. Caso hajam recursos humanos para criação de APPs específicos para telefones o domínio será a fonte de dados deste APP mas com funcionalidades específicas.

**Comment by joepreludian** [comment]
Não entendi o segundo questionamento. Você deixaria exposta uma API restful
JSON na outra ponta pra consumação dos dados?

Ficou um pouco nebuloso essa questão do WordPress. Teria um terceiro agente
criando o conteúdo. O WP seria um dos canais pra apresentar esses
infográficos. Isso?

Obrigado, amigo.

**Comment by ghost** [comment]
Opa!
É assim mesmo, simples! hehe
O Blog será o canal de distribuição do conteúdo a partir dos posts, e se tivermos mão de obra, poder embutir os infográficos nestes mesmos posts, enriquecendo o conteúdo.
E processos externos de retaguarda tanto no servidor ou numa máquina local, podem criar e editar os posts via API do próprio blog a partir do MySQL que em outro momento, recebeu várias integrações de outras fontes de dados.
Valeu!

**Comment by ghost** [comment]
fechado por mudança de escopo
