### ISSUE TITLE
desenv-db-access - Form - Importar arquivos de modelo gráfico (SVG) para layout de Infográfico

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#13]
Desenvolvimento de formulário MS Access (CRUD) para carga dos arquivos de modelo gráfico no formato SVG e respectiva miniatura  a serem utilizados pelos layouts.

![image](https://user-images.githubusercontent.com/34185310/37548652-2471b102-2958-11e8-8dcc-3e6acda48dbe.png)

**Comment by joepreludian** [comment]
Nesse caso era bom exportar esses dados por meio de JSON, além do SVG.
