### ISSUE TITLE
desenv-db-access | Exportar arquivo SVG para imagem PNG

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#14]
Será utilizado como editor e gerador de imagens vetoriais o Inkscape (https://inkscape.org/pt-br/) que é um software livre para editoração eletrônica de imagens e documentos vetoriais SVG.

O Access gerará automaticamente os infográficos a partir do processamento por linha de comando para cada registro definido em layout, e descarregará os dados de cada item de máscara no elemento dentro do SVG com o respectivo ID e na propriedade definida.

![image](https://user-images.githubusercontent.com/34185310/37556637-95278cf8-29d7-11e8-9aa7-5422785c42d6.png)

**Comment by joepreludian** [comment]
Editando o XML à partir do MS Access, sir? Muito bom!

**Comment by ghost** [comment]
legal né! hehe

**Comment by ghost** [comment]
demanda fechada por mudança de escopo, os posts do blog no decorrer de seu desenvolvimento evoluirão naturalmente para um infográfico, haja visto utilização de elementos visuais nos comparativos entre os políticos.
