### ISSUE TITLE
desenv-db-access | Form - Sincronização de tabelas MySQL > Access

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#15]
Incluir função no Form Access Sincronização de Dados, para que as informações sejam atualizadas a partir do banco de dados Oficial da OPS em MySQL.

Para isso veja como conectar a este banco.

O intuito do banco de dados Access local é fomentar e disponibilizar uma ferramenta aberta sobre política, para pesquisadores, estudantes, jornalistas e qualquer cidadão que queira fiscalizar seus representantes.

**Comment by joepreludian** [comment]
Há a opção de se utilizar mecanismos de automação como o travis CI pra isso?

**Comment by ghost** [comment]
Se o travis conseguir abrir o Access, instanciar e executar VBAs acho que não tem problemas.

**Comment by ghost** [comment]
demanda fechada por mudança de escopo.
O Access inicial foi dividido, onde todas as tabelas foram migradas e vinculadas ao MySQL, restando ao Access somente os dataentry (forms) e tratativas como importação e conversão de imagens base64 e funções específicas.

**Comment by joepreludian** [comment]
Quanto à tarefa do Travis carregar o MSAccess acho pouco provável, uma vez
que ele usa um ambiente baseado em Linux.

Ja o lance do MySQL é totalmente possivel. Tipo ele montar um banco mysel,
importar os dados do SQL, executar todas as ações de banco de dados, gerar
os JSON e exportar os JSON para um S3 da vida, por exemplo.

Totalmente possivel! Eu até gosto que seja assim pq vc mata o servidor da
jogada. =D
(E assim criamos uma abordagem Serveless)
