### ISSUE TITLE
desenv-db-access | Form Infográfico - Parametrização Layout, mascara e atributos

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#17]
Elaboração do Form responsável por definir, parametrizar e pré visualizar os atributos que serão plotados nos arquivos gráficos SVG dos infográficos 

![image](https://user-images.githubusercontent.com/34185310/37560683-a8860b14-2a1b-11e8-9272-a61876f84eff.png)

**Comment by joepreludian** [comment]
Esse Screenshot é de um projeto em do Access? =)

**Comment by ghost** [comment]
Isso msm é da tela do form de configuração do infográfico

**Comment by ghost** [comment]
demanda fechada por mudança de escopo para o conceito de "carrinho" onde os produtos que são os posts, ou seja os políticos, serem comparados via blogger.
