### ISSUE TITLE
🔥 plano-sistema | Priorizar geração dos infográficos a partir do MS Access com upload das imagens para WordPress

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#18]
**Diagrama Conceitual**
![plataforma inicial](https://raw.githubusercontent.com/ops-org/projeto-novo-eleitor/master/plano-sistema/plataforma.png)

## A data limite para prototipação da página responsiva em ASP/MySQL (item (2) do diagrama) foi alcançada sem sucesso e nem codificação inicial, somente o espelhamento do banco de dados Access para o MySQL

**Diante desta situação as demais partes do sistema **_(4)(3)(2)_** não terão mais prioridade, e não serão mais atualizadas a partir dos trabalhos elaborados no MS Access. E só serão continuadas se houverem voluntários empenhados com a causa para que estas áreas sejam integradas, construídas e entregues.**

Concentrarei os esforços do projeto somente para os itens (1) e (5) do diagrama conceitual sendo:

**- Arte e Design**
- [ ] Diagramação dos modelos de infográficos em SVG

**- Banco de Dados Access (0)(6)(1)**
- [ ] Integrações de dados Dados Abertos / IBGE / Senado / Câmara / Outros...
- [ ] Administração de dados sobre políticos e relações
- [ ] Geração dos infográficos via gerador em MS Access
- [ ] Exportação/upload das imagens de infográficos para o WordPress

**Comment by joepreludian** [comment]
So curiosidade. No caso o upload seria pro Blogger. Isso? Obrigado!

**Comment by ghost** [comment]
Isso msm 👍

**Comment by ghost** [comment]
Demanda fechada por mudança de escopo para blogger
