### ISSUE TITLE
desenv-blogger | Design e programação template padrão

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#26]
- [ ] **Definição do template para padrões visuais / usabilidade, considerar também que o template seja responsivo para mobile;**

- [ ] **Programação JS comparações entre 3 candidatos no máximo;**

- [ ] **Definir os padrões de dados json que serão salvos em cada post de candidato a partir do MySQL;**

**Comment by joepreludian** [comment]
Caro Alex,

Em cada postagem teremos como armazenar um objeto JSON com as informações
do usuário? Se isso for verdade será ótimo para a aplicação mobile, pq
apenas pegaria esse dado.

-Joey

**Comment by ghost** [comment]
Do usuário não, do político sim.
A idéia discutida na reunião via skype é de embutir no post o json com os dados do político e tratar a exibição no template

**Comment by ghost** [comment]
Demanda fechada por mudança de escopo
