### ISSUE TITLE
plano-sistema | Plano Blogger

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#28]
Atualização do projeto para Plano com Blogger

![Diagrama](https://raw.githubusercontent.com/ops-org/projeto-novo-eleitor/master/plano-sistema/plataforma1.jpg)
[https://github.com/ops-org/projeto-novo-eleitor/blob/master/plano-sistema/README.md]

1º - Matriz de Dados
Utilizaremos o MySQL como fonte/origem dos dados, e quaisquer soluções tecnológicas que escolhermos se servirá desta fonte de dados somente. 

2 º - Versão do MySQL
Vamos eleger a versão mais recente possível que estiver disponível em algum serviço web tipo AWS ou digitaloceam para mantermos o banco espelho que ficará em algum serviço a título de se ter um banco para desenvolvedores e pesquisadores.

3 º - Banco Mestre / Espelho
O banco PNE Mestre será um MySQL com a última versão disponível, provavelmente a 8.
Este banco será instalado de forma local com todos os dados e processos do PNE. Será mantido temporariamente pelo Alex Kiredjian até que os processos se estabilizem. Dado isso, o banco e todos os processos serão enviados para o Lúcio Big, o qual será o mantenedor/operador do PNE ou a quem delegar, ou  até que a OPS tenha condições financeiras de manter uma estrutura de TI para suportar o PNE na web como serviço.

4º - Banco Espelho
Como o próprio nome diz é o espelho do banco mestre com as ultimas atualizações e dados recebidos. Esta instância servirá para os desenvolvedores possam acessar e realizar testes, criar relatórios, fazer análises e etc, disponível em web.

5º - Processos de integração de dados
Todos os processos de integração (entrada/saída) serão elaborados para ambiente Windows a partir de chamadas de console para utilitários que farão as conexões necessárias para obtenção ou envio de dados como o curl.exe ou NodeJS, no qual via interface em MsAccess ou serviço na máquina Mestre será disparado o respectivo processo de integração. E tais processos farão a leitura do banco MySQL Matriz para suas integrações como por exemplo alimentar o Blogger via API com os políticos

**Comment by joepreludian** [comment]
Só pra deixar registrado, as tarefas vão rolar em cima do banco de dados de espelho, tá? Este é somente leitura, certo? Obrigado!

Vou criar uma nova tarefa para o sistema de sincronização em nuvem.

**Comment by ghost** [comment]
Demanda fechada por mudança de escopo
