### ISSUE TITLE
arte-e-design | Design de interface responsiva para App Mobile/Desktop, com comparativos e infográficos

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#4]
Diagramação inicial da interface responsiva para App Mobile/Desktop
[Quadro Arte e Design](https://github.com/ops-org/projeto-novo-eleitor/projects/1)

![Modelo](https://github.com/ops-org/projeto-novo-eleitor/blob/master/arte-e-design/interface-app/Interface%20responsiva%20app-mobile-desktop.png?raw=true)

**Comment by joepreludian** [comment]
@alexkiredjian Já existe algum projeto em andamento no sistema de frontend?
Com esse lance de infográficos e etc?

**Comment by ghost** [comment]
Olá @joepreludian até o momento esta atividade está suspensa, falta de recursos...

**Comment by joepreludian** [comment]
Opa,

Pois ótimo. Vou tentar pegar essa vertente. Agora estava em duvida numa
coisa: como já tenho habilidade em Ionic eu posso montar todas as telas com
uma fonte de dados em mockup. Pra irmos vendo por essa ponta. Uma vez o APP
funcionando podemos estender a logica pro desktop.

E só depois montar uma versão Android nativa (meu objeto de estudo
atualmente)

Por hora, como não tem nada definido em layout, eu vou montando as telas
com base nos componentes padrão e coloco pra vcs darem uma olhada.

Ah... O que acham de usar isto como referencia pra montar as telas? Acho
uma boa.

https://play.google.com/store/apps/details?id=com.material.components

Obrigado. :)

**Comment by ghost** [comment]
Legal isso heim.
Você conseguiria fazer um app tipo "carcaça" com 3 ou 4 telas, que só irá apresentar o conteúdo responsivo do blog para mobile?
Digo isso pois vamos concentrar a programação a entrega dos dados via próprio blog, a fim de centralizar e reduzir a carga de programação. 
E o aplicativo no primeiro momento exibiria o conteúdo do blog, mas com cara de app, e teria algumas funções especiais como compartilhar o post com watts e etcc.., registrar preferências, enviar depoimentos etc... tudo isso integrado com o blog.
o que acha?
valeu

**Comment by joepreludian** [comment]
Claro. Ótima ideia. Podemos utilizar a API restful do WordPress da ops pra
que eu possa coletar as informações. Espero que o site não esteja tão
poluído. Isso seria um problema pra processar no APP.

Darei inicio no projeto usando um flow padrão de git com PR, abrindo um
novo projeto e montando a tela inicial. Também irei colocar um serviço de
build e cobertura por testes.

Excelente trabalho. Depois quero ver como estão montando os infográficos.
Podemos ate usar nossas maquinas pra processar e jogar os resultados como
um JSON em um servidor de paginas estático, (como o próprio githib pages) e
assim criar uma abordagem serveless.

(Irei debulhar melhor a ideia depois)

Abraço. :)

**Comment by ghost** [comment]
Show! @joepreludian  Vamos nos falando. 
Me passe teu Telegram para lhe add ao grupo do Blogger no Telegram.
Por conveniência decidimos utilizar o Blogger para dar inicio aos trabalhos, se não, não saímos do lugar.

https://projetonovoeleitor.blogspot.com.br/

Lhe interessa a tarefa de criar o processo para incluir e alterar posts via API 3.0 do blogger via spool do MySQL? 

API 3.0 blogger, Já criei a key para o projeto, se lhe interessar o desafio lhe passo ela por telegram ;)
https://developers.google.com/blogger/docs/3.0/reference/posts/insert?apix=true


Abs!

**Comment by joepreludian** [comment]
Claro! No caso vai ser utilizado o Blogger memso para bucar as notícias? Então ótimo! =)
Vou iniciar o projeto por hoje. Quanto ao grupo do Telegram, eu já me encontro no Ops Dev Telegram. =)

Mandei msg pra você no seu telegram Btw.
https://t.me/jjrt42

**Comment by ghost** [comment]
joia! vamo q vamo!

**Comment by ghost** [comment]
Demanda fechada por mudança de escopo
